export const FETCH_MAZES = 'FETCH_MAZES';
export const FETCH_MAZE_SUCCESS = 'FETCH_MAZE_SUCCESS';
export const FETCH_MAZE_FAILURE = 'FETCH_MAZE_FAILURE';
export const CREATE_MAZE_SUCCESS = 'CREATE_MAZE_SUCCESS';
export const CREATE_MAZE_FAILURE = 'CREATE_MAZE_FAILURE';
export const MOVE_SUCCESS = 'MOVE_SUCCESS';
export const MOVE_FAILURE = 'MOVE_FAILURE';